name: weatherbench
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - xarray=0.13.0
  - netcdf4=1.5.2
  - dask=2.3.0
  - xesmf=0.2.0
  - fire=0.2.1
  - numpy=1.16.0
  - matplotlib=3.1.2
  - seaborn=0.9.0
  - configargparse=0.15.1
  - tensorflow=0.14
  - pip:
      - cdsapi=0.2.3
